# Generated by Django 3.1b1 on 2020-08-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_text', models.CharField(max_length=200)),
                ('difficulty_level', models.IntegerField()),
            ],
        ),
    ]
