# Generated by Django 3.1b1 on 2020-08-25 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Habit',
            new_name='Habits',
        ),
        migrations.RenameModel(
            old_name='Task',
            new_name='Tasks',
        ),
    ]
