# Generated by Django 3.1.1 on 2020-09-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0005_auto_20200910_0821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habititem',
            name='habit_list',
        ),
        migrations.AddField(
            model_name='habititem',
            name='habit_list',
            field=models.ManyToManyField(to='habits.HabitList'),
        ),
        migrations.RemoveField(
            model_name='taskitem',
            name='task_list',
        ),
        migrations.AddField(
            model_name='taskitem',
            name='task_list',
            field=models.ManyToManyField(to='habits.TaskList'),
        ),
    ]
