# Generated by Django 3.1.1 on 2020-09-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_auto_20200913_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habititem',
            old_name='habit_text',
            new_name='habit_name',
        ),
        migrations.RenameField(
            model_name='taskitem',
            old_name='task_text',
            new_name='task_name',
        ),
        migrations.RemoveField(
            model_name='habititem',
            name='habit_list',
        ),
        migrations.RemoveField(
            model_name='taskitem',
            name='task_list',
        ),
        migrations.AddField(
            model_name='habitlist',
            name='habit_items',
            field=models.ManyToManyField(to='habits.HabitItem'),
        ),
        migrations.AddField(
            model_name='taskitem',
            name='difficulty_level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasklist',
            name='task_items',
            field=models.ManyToManyField(to='habits.TaskItem'),
        ),
    ]
