# Generated by Django 3.1.1 on 2020-09-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0007_auto_20200913_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habititem',
            name='difficulty_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='taskitem',
            name='difficulty_level',
            field=models.IntegerField(default=1),
        ),
    ]
