# Generated by Django 3.1.1 on 2020-09-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_auto_20200913_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=200)),
            ],
        ),
    ]
