# Generated by Django 3.1.1 on 2020-09-13 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0009_filler'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filler',
        ),
    ]
